In [11]:
import pandas as pd
import random
import numpy as np

In [5]:
df = pd.read_csv("data/bank_transactions.csv")
df

,TransactionID,CustomerID,CustomerDOB,CustGender,CustLocation,CustAccountBalance,TransactionDate,TransactionTime,TransactionAmount (INR)
0,T1,C5841053,10/1/94,F,JAMSHEDPUR,17819.05,2/8/16,143207,25.0
1,T2,C2142763,4/4/57,M,JHAJJAR,2270.69,2/8/16,141858,27999.0
2,T3,C4417068,26/11/96,F,MUMBAI,17874.44,2/8/16,142712,459.0
3,T4,C5342380,14/9/73,F,MUMBAI,866503.21,2/8/16,142714,2060.0
4,T5,C9031234,24/3/88,F,NAVI MUMBAI,6714.43,2/8/16,181156,1762.5
...,...,...,...,...,...,...,...,...,...
1048562,T1048563,C8020229,8/4/90,M,NEW DELHI,7635.19,18/9/16,184824,799.0
1048563,T1048564,C6459278,20/2/92,M,NASHIK,27311.42,18/9/16,183734,460.0
1048564,T1048565,C6412354,18/5/89,M,HYDERABAD,221757.06,18/9/16,183313,770.0
1048565,T1048566,C6420483,30/8/78,M,VISAKHAPATNAM,10117.87,18/9/16,184706,1000.0
1048566,T1048567,C8337524,5/3/84,M,PUNE,75734.42,18/9/16,181222,1166.0

In [12]:
df["CustomerID"] = np.random.randint(1, 499, size=len(df))

In [13]:
df

,TransactionID,CustomerID,CustomerDOB,CustGender,CustLocation,CustAccountBalance,TransactionDate,TransactionTime,TransactionAmount (INR)
0,T1,282,10/1/94,F,JAMSHEDPUR,17819.05,2/8/16,143207,25.0
1,T2,451,4/4/57,M,JHAJJAR,2270.69,2/8/16,141858,27999.0
2,T3,198,26/11/96,F,MUMBAI,17874.44,2/8/16,142712,459.0
3,T4,249,14/9/73,F,MUMBAI,866503.21,2/8/16,142714,2060.0
4,T5,183,24/3/88,F,NAVI MUMBAI,6714.43,2/8/16,181156,1762.5
...,...,...,...,...,...,...,...,...,...
1048562,T1048563,86,8/4/90,M,NEW DELHI,7635.19,18/9/16,184824,799.0
1048563,T1048564,379,20/2/92,M,NASHIK,27311.42,18/9/16,183734,460.0
1048564,T1048565,328,18/5/89,M,HYDERABAD,221757.06,18/9/16,183313,770.0
1048565,T1048566,171,30/8/78,M,VISAKHAPATNAM,10117.87,18/9/16,184706,1000.0
1048566,T1048567,459,5/3/84,M,PUNE,75734.42,18/9/16,181222,1166.0